"""Runtime shadows of formally specified operation contracts.

The Lean files own the mathematical distinction between exact operation
semantics and the weaker relation established by local validation.  These
immutable values make that same distinction inspectable at the Python
boundary.  They are plans and audit data, not proof objects.

Operation-local checks stay separate from claim-side transport obligations: a
correct output is not by itself a proof that an arbitrary proposition can be
stated at the target.
"""

from dataclasses import dataclass
from types import MappingProxyType

from . import kernel as K


@dataclass(frozen=True)
class ValidationObligation:
    """One independently checkable part of an operation's local guarantee."""

    name: str
    verifier_subject: str
    verifier_function: str
    establishes: str


@dataclass(frozen=True)
class PointTransportContract:
    """Point-relation projection of an operation's semantic contract.

    Baseline capabilities feed the derived transport compiler. Conditional
    capabilities name authority that a separate verifier may earn. Predicate
    transport additionally names its claim transformer; capability booleans
    alone cannot relate predicates in different point spaces.
    """

    relation: str
    total: bool
    point_surjective: bool
    predicate_transformer: str
    conditional_capabilities: tuple


@dataclass(frozen=True)
class OperationContract:
    """Backend-neutral semantic and validation boundary for an operation."""

    kind: str
    source_sort: str
    target_sort: str
    parameters: tuple
    preconditions: tuple
    semantic_relation: str
    edge_type: str
    built_endpoint: str
    point_transport: PointTransportContract
    source_endpoint: str
    transport_reason: str
    checked_obligations: tuple
    transport_obligations: tuple
    open_obligations: tuple
    licensed_consequences: tuple

    def __post_init__(self):
        if self.edge_type not in K.ALL_TYPES:
            raise ValueError("%s names unknown edge type %s"
                             % (self.kind, self.edge_type))
        if {self.built_endpoint, self.source_endpoint} != {"src", "dst"}:
            raise ValueError("%s must orient built and source endpoints"
                             % self.kind)
        names = [obligation.name for obligation in self.checked_obligations]
        if len(names) != len(set(names)):
            raise ValueError("%s repeats a checked obligation" % self.kind)
        if not self.semantic_relation or not self.checked_obligations:
            raise ValueError("%s is missing semantics or validation" % self.kind)

        point = self.point_transport
        if not point.relation or not point.predicate_transformer:
            raise ValueError("%s is missing point semantics" % self.kind)
        declared = (point.total, point.point_surjective)
        baseline = K.point_relation_capabilities(self.edge_type)
        if declared != baseline:
            raise ValueError(
                "%s point capabilities %r disagree with %s baseline %r; "
                "stronger evidence belongs in conditional_capabilities"
                % (self.kind, declared, self.edge_type, baseline)
            )

    @property
    def derivation(self):
        return self.edge_type, self.transport_reason


@dataclass(frozen=True)
class PartitionContract:
    """Contract for one parent and an indexed branch family.

    This is intentionally not an ``OperationContract``: a partition's useful
    theorem is n-ary and no single branch edge carries its conclusion.
    """

    kind: str
    parent_sort: str
    branch_sort: str
    parameters: tuple
    preconditions: tuple
    semantic_relation: str
    branch_edge_type: str
    checked_obligations: tuple
    open_obligations: tuple
    licensed_consequences: tuple

    def __post_init__(self):
        if self.branch_edge_type not in K.ALL_TYPES:
            raise ValueError("%s names unknown branch edge type %s"
                             % (self.kind, self.branch_edge_type))
        if not self.semantic_relation or not self.checked_obligations:
            raise ValueError("%s is missing partition semantics or validation"
                             % self.kind)
        names = [obligation.name for obligation in self.checked_obligations]
        if len(names) != len(set(names)):
            raise ValueError("%s repeats a checked obligation" % self.kind)

SATURATION = OperationContract(
    kind="SaturateClosure",
    source_sort="ideal in an exact polynomial ring",
    target_sort="ideal in the same exact polynomial ring",
    parameters=("polynomial f",),
    preconditions=(
        "source and built ideals are interpreted in the same ring",
        "f is an expression in that ring",
        "the built ideal is generated by exactly the recorded output generators",
    ),
    semantic_relation="I(built) = I(source) : f^oo",
    edge_type=K.NECESSARY_CONDITION,
    point_transport=PointTransportContract(
        relation="literal same-coordinate inclusion of solution points",
        total=True,
        point_surjective=False,
        predicate_transformer="the same predicate in the shared coordinates",
        conditional_capabilities=(),
    ),
    built_endpoint="src",
    source_endpoint="dst",
    transport_reason=(
        "I : f^oo contains I, so the saturated model is cut by more "
        "equations; returning to the ambient model drops them"
    ),
    checked_obligations=(
        ValidationObligation(
            "source_containment",
            "edge",
            "containment",
            "I(source) is contained in I(built)",
        ),
        ValidationObligation(
            "no_invented_generators",
            "operation",
            "operation_output",
            "every recorded generator of I(built) has a certified witness "
            "in I(source) : f^oo",
        ),
    ),
    transport_obligations=(),
    open_obligations=(
        "I(source) : f^oo is contained in I(built) (output completeness)",
    ),
    licensed_consequences=(
        "the entire built ideal is contained in I(source) : f^oo "
        "(generator certificates lift through ideal generation)",
        "source ideal identities hold on the built model "
        "(NECESSARY_CONDITION/AGAINST)",
    ),
)


ELIMINATION = OperationContract(
    kind="Eliminate",
    source_sort="ideal in source exact polynomial ring R",
    target_sort="ideal in retained-coordinate exact polynomial ring S",
    parameters=(
        "coordinate inclusion S -> R",
        "eliminated/retained variable partition",
    ),
    preconditions=(
        "retained and eliminated variables are disjoint and partition the source ring",
        "source and built rings have the same exact coefficient domain",
        "the built ideal is generated by exactly the recorded output generators",
    ),
    semantic_relation="I(built) = inclusion^-1(I(source))",
    edge_type=K.IMAGE_CLOSURE,
    built_endpoint="dst",
    point_transport=PointTransportContract(
        relation="retained-coordinate projection from source to target points",
        total=True,
        point_surjective=False,
        predicate_transformer=(
            "exact pullback along projection; along transport requires a "
            "target-expressible predicate and geometric or lifting authority"
        ),
        conditional_capabilities=(
            "point_surjective after a verified section or finite lift cover",
        ),
    ),
    source_endpoint="src",
    transport_reason=(
        "exact elimination contracts the source ideal to the retained-coordinate "
        "ring; a polynomial section additionally supplies target-point lifts, "
        "while a pure Groebner certificate supplies only ideal equality"
    ),
    checked_obligations=(
        ValidationObligation(
            "generator_expressibility",
            "operation",
            "operation_output",
            "every recorded output generator is an expression in the retained ring",
        ),
        ValidationObligation(
            "generator_source_membership",
            "operation",
            "operation_output",
            "every recorded output generator maps into the source ideal",
        ),
        ValidationObligation(
            "section_completeness",
            "elimination",
            "elimination_section",
            "a polynomial retraction fixes the retained ring and carries the "
            "entire source ideal into the recorded target ideal",
        ),
        ValidationObligation(
            "groebner_completeness",
            "elimination",
            "elimination_groebner",
            "a pure-lex basis certificate checks each recorded source generator's "
            "basis-span identity, "
            "bounded S-pair representation, and retained-basis membership",
        ),
        ValidationObligation(
            "piecewise_point_lift",
            "point_lift",
            "elimination_point_lift",
            "principal-open rational lift charts plus an all-guards-zero "
            "fallback jointly cover the target; exact radical/localization "
            "identities prove every chart lands in the source",
        ),
    ),
    transport_obligations=(
        ValidationObligation(
            "retained_coordinate_expressibility",
            "claim",
            "structured_condition",
            "the source predicate is an exact ZERO/NONZERO conjunction whose "
            "expressions also parse in the retained-coordinate target ring",
        ),
    ),
    open_obligations=(
        "contraction completeness beyond Q/prime fields, bounded pure lex, and polynomial sections",
        "explicit concrete point maps for nonidentity refinements and base changes",
    ),
    licensed_consequences=(
        "the entire built ideal is contained in the contraction of the source ideal",
        "target identities pull back to source identities (IMAGE_CLOSURE/AGAINST)",
        "source points map to target points, so target emptiness implies source emptiness",
        "a verified section or Groebner certificate plus no-invention licenses source-derived retained-ring identities along",
        "a verified global section or finite piecewise lift cover plus no-invention supplies point-surjective image authority over the declared coefficient field",
        "point-surjectivity transports structured retained-coordinate predicates, including NONZERO atoms, after exact equivalence rewriting or concrete point-map pullback",
    ),
)


AFFINE_COORDINATE_SOLVE = OperationContract(
    kind="AffineCoordinateSolve",
    source_sort="ideal model with one literal unit-coefficient affine equation",
    target_sort="same model in translated coordinates with the pivot equal to zero",
    parameters=("pivot coordinate", "pivot solution", "target model id"),
    preconditions=(
        "the pivot is a declared ring variable",
        "the solution is a polynomial independent of the pivot",
        "pivot - solution is literally one source generator",
        "every source generator is simultaneously rewritten by the inverse translation",
    ),
    semantic_relation=(
        "the source and target coordinate rings are isomorphic under the "
        "mutually inverse affine translations"
    ),
    edge_type=K.EQUIVALENCE,
    built_endpoint="dst",
    source_endpoint="src",
    point_transport=PointTransportContract(
        relation="mapped equivalence under inverse affine translations",
        total=True,
        point_surjective=True,
        predicate_transformer="rewrite through the checked inverse point map",
        conditional_capabilities=(),
    ),
    transport_reason=(
        "subtracting the pivot solution is an invertible polynomial coordinate "
        "translation; its inverse adds the same pivot-independent polynomial"
    ),
    checked_obligations=(
        ValidationObligation(
            "literal_affine_definition", "operation", "constructor",
            "pivot - solution is exactly a recorded source generator",
        ),
        ValidationObligation(
            "simultaneous_generator_rewrite", "operation", "constructor",
            "every target generator is the exact inverse-map rewrite of one source generator",
        ),
        ValidationObligation(
            "coordinate_ring_isomorphism", "ring_iso", "ring_iso",
            "both ideal pullbacks and both coordinate-map round trips verify",
        ),
    ),
    transport_obligations=(),
    open_obligations=(
        "affine pivots whose coefficient is a nonconstant declared unit",
        "dropping the normalized zero coordinate into a smaller polynomial ring",
    ),
    licensed_consequences=(
        "source and target point claims transport in both directions",
        "structured identities rewrite only after the ring-isomorphism verdict is VERIFIED",
        "the normalized pivot is zero on the target presentation",
    ),
)

PRODUCT_SPLIT_PARTITION = PartitionContract(
    kind="ProductSplit",
    parent_sort="ideal model in one exact polynomial ring",
    branch_sort="two same-ring models obtained by adjoining one factor",
    parameters=(
        "verified binary product receipt",
        "selected receipt id",
        "left and right branch ids",
    ),
    preconditions=(
        "the receipt ring and characteristic equal the parent declarations",
        "the selected equation is literally a recorded parent generator",
        "the selected scalar is a nonzero constant coefficient",
    ),
    semantic_relation=(
        "V(parent) = V(parent + (left)) union V(parent + (right))"
    ),
    branch_edge_type=K.NECESSARY_CONDITION,
    checked_obligations=(
        ValidationObligation(
            "binary_product_identity", "receipt", "verify-product-split",
            "equation = scalar * left * right exactly",
        ),
        ValidationObligation(
            "parent_equation_binding", "operation",
            "product_split_constructor",
            "the checked equation is a literal generator of the parent ideal",
        ),
        ValidationObligation(
            "constant_unit_scalar", "operation", "product_split_constructor",
            "the scalar is a nonzero coefficient unit, so no open-locus "
            "coverage premise is hidden",
        ),
        ValidationObligation(
            "partition_exhaustiveness", "partition",
            "partition_exhaustiveness",
            "the two recorded branch ideals cover the parent",
        ),
    ),
    open_obligations=(
        "localized product covers whose scalar contains declared open units",
        "non-literal parent ideal membership with a checked cofactor witness",
    ),
    licensed_consequences=(
        "two branch models, each included in the parent",
        "a verifier-decidable claim that the branches jointly cover the parent",
        "partition recombination only after the existing n-ary kernel rule "
        "sees every branch conclusion and VERIFIED exhaustiveness",
    ),
)

CONTRACTS = MappingProxyType({
    SATURATION.kind: SATURATION,
    ELIMINATION.kind: ELIMINATION,
    AFFINE_COORDINATE_SOLVE.kind: AFFINE_COORDINATE_SOLVE,
})


PARTITION_CONTRACTS = MappingProxyType({
    PRODUCT_SPLIT_PARTITION.kind: PRODUCT_SPLIT_PARTITION,
})

def for_operation(kind):
    """Return the formalization-backed runtime contract, if one exists."""

    return CONTRACTS.get(kind)
