$ErrorActionPreference='Stop'
Set-Location -LiteralPath 'spikes/mathlib-binding'
$manifest=Get-Content -LiteralPath 'lake-manifest.json' -Raw|ConvertFrom-Json
$deps=foreach($package in $manifest.packages){$head=git -C ".lake/packages/$($package.name)" rev-parse HEAD;[pscustomobject]@{name=$package.name;url=$package.url;locked_revision=$package.rev;actual_head=$head;matches=($head -eq $package.rev)}}
$files=@('README.md','Binding.lean','A08Timing.lean','A05Timing.lean','lakefile.toml','lean-toolchain','lake-manifest.json','environment.ps1','Measure.ps1','MeasureCases.ps1','RecordProvenance.ps1','Validate.ps1','.lake/packages/mathlib/LICENSE','.lake/packages/mathlib/lean-toolchain','.lake/packages/mathlib/lake-manifest.json','.lake/packages/mathlib/Mathlib/Algebra/Ring/Defs.lean','.lake/packages/mathlib/Mathlib/Logic/Nontrivial/Defs.lean','.lake/packages/mathlib/Mathlib/Algebra/CharP/Defs.lean','.lake/packages/mathlib/Mathlib/Data/ZMod/Defs.lean','.lake/packages/mathlib/Mathlib/Algebra/Field/ZMod.lean','.lake/build/lib/lean/Binding.olean','.lake/build/lib/lean/A08Timing.olean','.lake/build/lib/lean/A05Timing.olean','$ELAN_HOME/toolchains/leanprover--lean4---v4.32.1/bin/lean.exe','$ELAN_HOME/toolchains/leanprover--lean4---v4.32.1/bin/lake.exe','$ELAN_HOME/toolchains/leanprover--lean4---v4.32.1/bin/leanchecker.exe','$ELAN_HOME/toolchains/leanprover--lean4---v4.32.1/src/lean/LeanChecker.lean')
$files+=@(Get-ChildItem -LiteralPath './logs' -File|Where-Object {$_.Name -notin @('provenance.json','validation.json')}|ForEach-Object {$_.FullName})
$hashes=foreach($f in $files){[pscustomobject]@{path=$f;sha256=(Get-FileHash -LiteralPath $f -Algorithm SHA256).Hash.ToLower()}}
$corpus=foreach($id in @('GP-A08b','GP-A05')){[pscustomobject]@{id=$id;path="../../corpus/must/$id.json";sha256=(Get-FileHash -LiteralPath "../../corpus/must/$id.json" -Algorithm SHA256).Hash.ToLower()}}
[pscustomobject]@{dependencies=@($deps);files=@($hashes);corpus_after=@($corpus);corpus_git_diff=@(git -C '../..' diff --name-only HEAD -- corpus)}|ConvertTo-Json -Depth 10|Set-Content -LiteralPath './logs/provenance.json' -Encoding utf8
