"""Executable correspondence tests for operation-contract runtime shadows."""

from dataclasses import FrozenInstanceError, replace

import pytest

from grandportage import cas
from grandportage import cli
from grandportage import check as C
from grandportage import contracts as OC
from grandportage import kernel as K
from grandportage import operations as O
from grandportage import store as S
from grandportage import verify as V


def test_saturation_contract_separates_semantics_from_checked_guarantees():
    contract = OC.SATURATION

    assert contract.semantic_relation == "I(built) = I(source) : f^oo"
    assert contract.edge_type == K.NECESSARY_CONDITION
    assert contract.built_endpoint == "src"
    assert contract.source_endpoint == "dst"

    checked = {obligation.name: obligation
               for obligation in contract.checked_obligations}
    assert set(checked) == {
        "source_containment",
        "no_invented_generators",
    }
    assert checked["source_containment"].verifier_subject == "edge"
    assert checked["source_containment"].verifier_function == "containment"
    assert checked["no_invented_generators"].verifier_subject == "operation"
    assert (checked["no_invented_generators"].verifier_function
            == "operation_output")
    for obligation in checked.values():
        assert obligation.verifier_subject in S.Graph._VERDICTS
        assert (S.Graph._VERDICTS[obligation.verifier_subject]["writer"]
                == "verify.%s" % obligation.verifier_function)
        assert callable(getattr(V, obligation.verifier_function))

    assert contract.transport_obligations == ()
    assert len(contract.open_obligations) == 1
    assert "completeness" in contract.open_obligations[0]
    assert all("complete" not in obligation.establishes.lower()
               for obligation in contract.checked_obligations)
    assert any("generated by exactly" in item
               for item in contract.preconditions)
    assert any("entire built ideal" in item
               for item in contract.licensed_consequences)


def test_saturation_contract_is_the_constructor_derivation_source():
    assert O.DERIVES["SaturateClosure"] == OC.SATURATION.derivation

    op = O.saturate_closure(
        "SOURCE", "x", "BUILT", ["x", "y"], ["x*y"],
    )
    assert op.contract is OC.SATURATION
    edge = op.events[1]
    assert edge["src"] == "BUILT"
    assert edge["dst"] == "SOURCE"
    assert edge["type"] == op.contract.edge_type
    assert edge["why"].startswith(op.contract.transport_reason)


def test_execution_preserves_the_semantic_contract():
    op = O.saturate_closure(
        "SOURCE", "x", "BUILT", ["x", "y"], ["x*y"],
    )

    def fake(program, _timeout):
        return {
            "aborted": False,
            "returncode": 0,
            "stderr": "",
            "stdout": ("@@GP_OUT:\nGP_OUT[1]=y\n"
                       + program.completion_marker + "\n"),
        }

    done = O.execute(op, _runner=fake)
    assert done.contract is OC.SATURATION
    assert done.events[0]["generators"] == ["y"]


def test_contract_values_are_immutable_audit_data():
    with pytest.raises(FrozenInstanceError):
        OC.SATURATION.semantic_relation = "whatever the backend returned"



@pytest.mark.parametrize(
    "contract", [OC.SATURATION, OC.ELIMINATION, OC.AFFINE_COORDINATE_SOLVE])
def test_operation_contracts_project_to_the_point_rule_compiler(contract):
    """Operation semantics, edge baselines, and claim typing stay distinct."""
    point = contract.point_transport
    assert (point.total, point.point_surjective) == (
        K.point_relation_capabilities(contract.edge_type))
    assert point.relation
    assert point.predicate_transformer

    for direction, kind in (
            (K.ALONG, K.NONEMPTY),
            (K.AGAINST, K.EMPTY),
            (K.AGAINST, K.PREDICATE)):
        assert K.compile_point_rule(
            contract.edge_type, direction, kind) is True

    if contract is OC.ELIMINATION:
        assert not point.point_surjective
        assert any("point_surjective" in item
                   for item in point.conditional_capabilities)
    else:
        assert point.conditional_capabilities == ()

def test_operation_contract_rejects_capability_inflation():
    inflated = replace(
        OC.SATURATION.point_transport,
        point_surjective=True,
        conditional_capabilities=(),
    )
    with pytest.raises(ValueError, match="stronger evidence belongs"):
        replace(OC.SATURATION, point_transport=inflated)

def test_incomplete_saturation_passes_local_checks_without_becoming_exact():
    """The runtime image of Lean's `(6) : 2^oo` counterexample.

    Saturating (x*y) at x is (y).  Recording the unchanged ideal (x*y) is
    therefore incomplete, but it satisfies both one-sided local checks: the
    source is contained in itself and its sole generator has an exponent-zero
    saturation witness.  No exactness authority may appear.
    """
    op = O.saturate_closure(
        "SOURCE", "x", "INCOMPLETE", ["x", "y"], ["x*y"],
    )

    def fake_execution(program, _timeout):
        return {
            "aborted": False,
            "returncode": 0,
            "stderr": "",
            "stdout": ("@@GP_OUT:\nGP_OUT[1]=x*y\n"
                       + program.completion_marker + "\n"),
        }

    done = O.execute(op, _runner=fake_execution)
    graph = S.Graph().apply_all([
        ({"ev": "model", "id": "SOURCE", "what": "source",
          "characteristic": 0, "ring_vars": ["x", "y"],
          "generators": ["x*y"]}, "test", 0),
    ] + [(event, "test", i + 1) for i, event in enumerate(done.events)])
    graph.validate()

    class LocallySoundIncompleteBackend:
        def classify_identity(self, *_args, **_kwargs):
            return K.DERIVED, {"reduced_modulo_ideal": "0"}

        def membership(self, _ring, polynomial, _generators, **_kwargs):
            assert polynomial == "x*y"
            return {"is_member": True, "reduced": "0", "cofactors": ["1"]}

    backend = LocallySoundIncompleteBackend()
    obligations = {item.name: item for item in done.contract.checked_obligations}
    containment_check = getattr(
        V, obligations["source_containment"].verifier_function)
    output_check = getattr(
        V, obligations["no_invented_generators"].verifier_function)
    containment, containment_why = containment_check(
        graph, "E-INCOMPLETE", _backend=backend)
    output, output_why, _certificate = output_check(
        graph, "E-INCOMPLETE", _backend=backend)

    assert containment == V.VERIFIED, containment_why
    assert output == V.OP_SOUND, output_why
    assert "DOES NOT SAY: that the output is COMPLETE" in output_why
    assert "completeness" in done.contract.open_obligations[0]
    assert all("semantic_relation" not in event and "exact" not in event
               for event in done.events)


def test_elimination_contract_is_multi_sorted_and_one_sided():
    contract = OC.ELIMINATION

    assert contract.edge_type == K.IMAGE_CLOSURE
    assert contract.built_endpoint == "dst"
    assert contract.source_endpoint == "src"
    assert contract.source_sort != contract.target_sort
    assert "inclusion^-1" in contract.semantic_relation
    assert {item.name for item in contract.checked_obligations} == {
        "generator_expressibility",
        "generator_source_membership",
        "section_completeness",
        "groebner_completeness",
        "piecewise_point_lift",
    }
    local = contract.checked_obligations[:2]
    exact = contract.checked_obligations[2:]
    assert all(item.verifier_subject == "operation"
               and item.verifier_function == "operation_output"
               for item in local)
    assert {item.verifier_subject for item in exact} == {
        "elimination", "point_lift",
    }
    assert {item.verifier_function for item in exact} == {
        "elimination_section", "elimination_groebner",
        "elimination_point_lift",
    }
    assert {item.name for item in contract.transport_obligations} == {
        "retained_coordinate_expressibility",
    }
    assert contract.transport_obligations[0].verifier_subject == "claim"
    assert "ZERO/NONZERO" in contract.transport_obligations[0].establishes
    assert any("completeness" in item for item in contract.open_obligations)
    assert any("verified section" in item.lower()
               and "identit" in item.lower()
               for item in contract.licensed_consequences)


def test_elimination_constructor_and_execution_preserve_the_contract():
    op = O.eliminate(
        "SOURCE", ["y"], "BUILT", ["x", "y"], ["x*y"])

    assert O.DERIVES["Eliminate"] == OC.ELIMINATION.derivation
    assert op.contract is OC.ELIMINATION
    assert op.events[1]["src"] == "SOURCE"
    assert op.events[1]["dst"] == "BUILT"

    def fake(program, _timeout):
        return {
            "aborted": False,
            "returncode": 0,
            "stderr": "",
            "stdout": "@@GP_OUT:\nGP_OUT[1]=0\n"
                      + program.completion_marker + "\n",
        }

    done = O.execute(op, _runner=fake)
    assert done.contract is OC.ELIMINATION
    assert done.events[0]["generators"] == []


def test_incomplete_elimination_passes_local_check_but_not_exact_contract():
    """Runtime pole matching Lean's `(2) -> (0)` counterexample.

    Eliminating y from (x) should return (x). The deliberately empty output
    has no invented generator, so the cheap checker passes vacuously; the
    contract must retain completeness as an open obligation.
    """
    op = O.eliminate(
        "SOURCE", ["y"], "INCOMPLETE", ["x", "y"], ["x"])

    def fake(program, _timeout):
        return {
            "aborted": False,
            "returncode": 0,
            "stderr": "",
            "stdout": "@@GP_OUT:\nGP_OUT[1]=0\n"
                      + program.completion_marker + "\n",
        }

    done = O.execute(op, _runner=fake)
    graph = S.Graph().apply_all([
        ({"ev": "model", "id": "SOURCE", "what": "source",
          "characteristic": 0, "ring_vars": ["x", "y"],
          "generators": ["x"]}, "test", 0),
    ] + [(event, "test", i + 1) for i, event in enumerate(done.events)])
    graph.validate()

    verdict, why, certificate = V.operation_output(graph, "E-INCOMPLETE")
    assert verdict == V.OP_SOUND, why
    assert certificate["targets"] == []
    assert certificate["target_ring_vars"] == ["x"]
    assert certificate["eliminated"] == ["y"]
    assert "DOES NOT SAY: that the output is COMPLETE" in why
    assert any("bounded pure lex" in item
               for item in done.contract.open_obligations)


def test_elimination_local_check_requires_an_exact_ring_partition():
    graph = S.Graph().apply_all([
        ({"ev": "model", "id": "SOURCE", "what": "source",
          "characteristic": 0, "ring_vars": ["x", "y"],
          "generators": ["x"]}, "test", 0),
        ({"ev": "model", "id": "BUILT", "what": "bad target",
          "characteristic": 0, "ring_vars": ["x", "z"],
          "generators": [], "eliminated": ["y"]}, "test", 1),
        ({"ev": "edge", "id": "E", "src": "SOURCE", "dst": "BUILT",
          "type": K.IMAGE_CLOSURE, "map_kind": K.POLYNOMIAL,
          "why": "claims to eliminate y", "built_by_operation": "Eliminate"},
         "test", 2),
    ]).validate()

    verdict, why, certificate = V.operation_output(graph, "E")
    assert verdict == V.UNVERIFIED
    assert "retained variables" in why
    assert certificate is None

def test_empty_elimination_output_records_its_checked_scope(
        tmp_path, monkeypatch):
    root = str(tmp_path)
    S.append([
        {"ev": "model", "id": "SOURCE", "what": "source",
         "characteristic": 0, "ring_vars": ["x", "y"],
         "generators": ["x"]},
        {"ev": "model", "id": "BUILT", "what": "empty output",
         "characteristic": 0, "ring_vars": ["x"],
         "generators": [], "eliminated": ["y"]},
        {"ev": "edge", "id": "E", "src": "SOURCE", "dst": "BUILT",
         "type": K.IMAGE_CLOSURE, "map_kind": K.POLYNOMIAL,
         "why": "eliminate y", "built_by_operation": "Eliminate"},
    ], root)
    backend = cas.SingularBackend(
        runner=lambda *_args: pytest.fail("empty output needs no CAS run"),
        binary_version="Singular 4.4.1")
    monkeypatch.setattr(
        cas.SingularBackend, "can_record_verdicts",
        property(lambda _self: True))

    V.verify_all(root=root, backend=backend, record=True)

    graph = S.load(S.graph_path(root))
    assert graph.edges["E"]["output_verdict"] == V.OP_SOUND
    assert graph.edges["E"]["representation"]["cofactors"] == []
    assert graph.edges["E"]["representation"]["eliminated"] == ["y"]

def test_local_elimination_verdict_does_not_mint_exact_forward_authority():
    graph = S.Graph().apply_all([
        ({"ev": "model", "id": "SOURCE", "what": "source",
          "characteristic": 0, "ring_vars": ["x", "y"],
          "generators": ["x"]}, "test", 0),
        ({"ev": "model", "id": "BUILT", "what": "incomplete target",
          "characteristic": 0, "ring_vars": ["x"],
          "generators": [], "eliminated": ["y"]}, "test", 1),
        ({"ev": "edge", "id": "E", "src": "SOURCE", "dst": "BUILT",
          "type": K.IMAGE_CLOSURE, "map_kind": K.POLYNOMIAL,
          "why": "eliminate y", "built_by_operation": "Eliminate"},
         "test", 2),
        ({"ev": "claim", "id": "C", "model": "SOURCE",
          "kind": K.IDENTITY, "statement": "x vanishes", "lhs": "x",
          "rhs": "0", "ring_vars": ["x"],
          "identity_origin": K.DERIVED}, "test", 3),
        ({"ev": "inference", "id": "I", "claim": "C",
          "path": [["E", K.ALONG]], "concludes_kind": K.IDENTITY,
          "asserted": "x vanishes on the recorded target"}, "test", 4),
    ]).validate()
    # This is exactly the verdict operation_output currently produces: local
    # no-invention, not contraction completeness.
    graph.edges["E"]["output_verdict"] = V.OP_SOUND

    licensed, trace = C.audit_inference(graph, "I")
    assert not licensed
    assert "completeness" in trace[0][3]

    graph.edges["E"].pop("built_by_operation")
    licensed, _trace = C.audit_inference(graph, "I")
    assert licensed, "an authored exact IMAGE_CLOSURE still states exactness"
class _SectionBackend:
    """Semantic test double for the section checker, never for persistence."""

    def __init__(self):
        self.pullbacks = []

    def pullback_reduce(self, ring, expression, images, generators=(), **_kw):
        assert ring == ["y", "x"]
        assert images == {"y": "x^2", "x": "x"}
        assert generators == []
        self.pullbacks.append(expression)
        return {
            "y*x-1": "x^3-1",
            "y^2-x": "x^4-x",
        }[expression], False

    def membership(self, ring, expression, generators, **_kw):
        assert ring == ["x"]
        assert generators == ["x^3-1"]
        return {
            "is_member": True,
            "reduced": "0",
            "cofactors": ["1" if expression == "x^3-1" else "x"],
        }

    def check_membership(self, ring, expression, generators, cofactors, **_kw):
        assert ring == ["x"]
        assert generators == ["x^3-1"]
        expected = ["1" if expression == "x^3-1" else "x"]
        return cofactors == expected, expression


def _section_graph():
    return S.Graph().apply_all([
        ({"ev": "model", "id": "SOURCE", "what": "source",
          "characteristic": 0, "ring_vars": ["y", "x"],
          "generators": ["y*x-1", "y^2-x"]}, "test", 0),
        ({"ev": "model", "id": "TARGET", "what": "elimination target",
          "characteristic": 0, "ring_vars": ["x"],
          "generators": ["x^3-1"], "eliminated": ["y"]}, "test", 1),
        ({"ev": "edge", "id": "E", "src": "SOURCE", "dst": "TARGET",
          "type": K.IMAGE_CLOSURE, "map_kind": K.POLYNOMIAL,
          "why": "eliminate y", "built_by_operation": "Eliminate"},
         "test", 2),
    ]).validate()


def test_polynomial_section_certifies_missing_contraction_inclusion():
    graph = _section_graph()
    verdict, why, certificate = V.elimination_section(
        graph, "E", {"y": "x^2"}, _backend=_SectionBackend())

    assert verdict == V.SECTION_VERIFIED, why
    assert certificate["method"] == "polynomial_section_v1"
    assert certificate["images"] == {"y": "x^2", "x": "x"}
    assert [row["cofactors"] for row in certificate["rows"]] == [["1"], ["x"]]
    assert "exact contraction" in why
    assert "explicit polynomial lift" in why


def test_section_and_no_invention_unlock_identity_and_point_surjectivity():
    graph = _section_graph()
    edge = graph.edges["E"]
    edge["contraction_verdict"] = V.SECTION_VERIFIED

    # A section is a target-point lift, but the recorded edge is not yet known
    # to receive every source point until no-invention is independently checked.
    assert not C.effective_exact_contraction(edge)
    assert not C.effective_geometric_closure(edge)

    edge["output_verdict"] = V.OP_SOUND
    assert C.effective_exact_contraction(edge)
    assert C.effective_geometric_closure(edge)
    assert C.effective_image_complete(edge)
    identity = K.transport(
        K.IMAGE_CLOSURE, K.ALONG, K.IDENTITY,
        map_kind=K.POLYNOMIAL,
        exact_contraction=C.effective_exact_contraction(edge),
        geometric_closure=C.effective_geometric_closure(edge))
    predicate = K.transport(
        K.IMAGE_CLOSURE, K.ALONG, K.PREDICATE,
        zariski_closed=True,
        exact_contraction=C.effective_exact_contraction(edge),
        geometric_closure=C.effective_geometric_closure(edge))
    assert identity.licensed
    assert predicate.licensed
    assert "geometric image-closure authority" in predicate.reason


def _condition_graph(expression=None, relation="NONZERO"):
    graph = _section_graph()
    claim = {"ev": "claim", "id": "P", "model": "SOURCE",
             "kind": K.PREDICATE, "statement": "the condition holds"}
    if expression is not None:
        claim["condition"] = {"all": [
            {"relation": relation, "expression": expression},
        ]}
    graph.apply(claim, source="test", lineno=3)
    graph.apply({"ev": "inference", "id": "I", "claim": "P",
                 "path": [["E", K.ALONG]],
                 "concludes_kind": K.PREDICATE,
                 "asserted": "the condition holds on the target"},
                source="test", lineno=4)
    graph.validate()
    graph.edges["E"]["output_verdict"] = V.OP_SOUND
    graph.edges["E"]["contraction_verdict"] = V.SECTION_VERIFIED
    return graph


def test_section_transports_target_expressible_nonvanishing_condition():
    graph = _condition_graph("x", relation="NONZERO")

    assert C.condition_expressible_at(graph, graph.claims["P"], "TARGET")
    assert not C.structured_condition_closed(graph.claims["P"])
    assert C.effective_point_surjective(graph.edges["E"])
    licensed, trace = C.audit_inference(graph, "I")
    assert licensed
    assert "closedness is not required" in trace[0][3]

    # The identity law is now executable: a literal identity-coordinate pass
    # preserves the structured syntax before the section-certified elimination.
    graph.apply({"ev": "model", "id": "PRE", "what": "prior presentation",
                 "characteristic": 0, "ring_vars": ["y", "x"],
                 "generators": ["y*x-1", "y^2-x"]},
                source="test", lineno=5)
    graph.apply({"ev": "edge", "id": "EQ", "src": "PRE", "dst": "SOURCE",
                 "type": K.EQUIVALENCE, "map_kind": K.IDENTITY_MAP,
                 "why": "same literal presentation"},
                source="test", lineno=6)
    graph.apply({"ev": "claim", "id": "P2", "model": "PRE",
                 "kind": K.PREDICATE, "statement": "x is nonzero",
                 "condition": {"all": [
                     {"relation": "NONZERO", "expression": "x"},
                 ]}}, source="test", lineno=7)
    graph.apply({"ev": "inference", "id": "I2", "claim": "P2",
                 "path": [["EQ", K.ALONG], ["E", K.ALONG]],
                 "concludes_kind": K.PREDICATE,
                 "asserted": "x is nonzero after two passes"},
                source="test", lineno=8)
    graph.validate()
    chained, chained_trace = C.audit_inference(graph, "I2")
    assert chained
    assert "identity point-map substitution" in chained_trace[0][3]
    assert "closedness is not required" in chained_trace[1][3]


def test_verified_mapped_equivalences_rewrite_conditions_and_compose():
    graph = _condition_graph("x", relation="NONZERO")
    for model_id in ("PRE1", "PRE2"):
        graph.apply({
            "ev": "model", "id": model_id, "what": "mapped presentation",
            "characteristic": 0, "ring_vars": ["y", "x"],
            "generators": ["y*x-1", "y^2-x"],
        }, source="test", lineno=5)
    graph.apply({
        "ev": "edge", "id": "EQ1", "src": "PRE1", "dst": "SOURCE",
        "type": K.EQUIVALENCE, "map_kind": K.POLYNOMIAL,
        "why": "translate x by one", "ring_iso": True,
        "forward": {"y": "y", "x": "x+1"},
        "inverse": {"y": "y", "x": "x-1"},
    }, source="test", lineno=6)
    graph.apply({
        "ev": "edge", "id": "EQ2", "src": "PRE2", "dst": "PRE1",
        "type": K.EQUIVALENCE, "map_kind": K.POLYNOMIAL,
        "why": "translate x by two", "ring_iso": True,
        "forward": {"y": "y", "x": "x+2"},
        "inverse": {"y": "y", "x": "x-2"},
    }, source="test", lineno=7)
    graph.apply({
        "ev": "claim", "id": "P3", "model": "PRE2",
        "kind": K.PREDICATE, "statement": "x+3 is nonzero",
        "condition": {"all": [
            {"relation": "NONZERO", "expression": "x+3"},
        ]},
    }, source="test", lineno=8)
    graph.apply({
        "ev": "inference", "id": "I3", "claim": "P3",
        "path": [["EQ2", K.ALONG], ["EQ1", K.ALONG], ["E", K.ALONG]],
        "concludes_kind": K.PREDICATE,
        "asserted": "x is nonzero after two coordinate changes",
    }, source="test", lineno=9)
    graph.validate()
    graph.edges["EQ1"]["ring_iso_verdict"] = V.ISO_VERIFIED
    graph.edges["EQ2"]["ring_iso_verdict"] = V.ISO_VERIFIED

    first, first_why = C.rewrite_condition_across_equivalence(
        graph, graph.claims["P3"]["condition"], graph.edges["EQ2"], K.ALONG)
    second, second_why = C.rewrite_condition_across_equivalence(
        graph, first, graph.edges["EQ1"], K.ALONG)
    assert first["all"][0]["expression"] == "x+1"
    assert second["all"][0]["expression"] == "x"
    assert "inverse point-map" in first_why
    assert "inverse point-map" in second_why
    against, against_why = C.rewrite_condition_across_equivalence(
        graph, {"all": [{"relation": "NONZERO", "expression": "x"}]},
        graph.edges["EQ1"], K.AGAINST)
    assert against["all"][0]["expression"] == "x+1"
    assert "forward point-map" in against_why

    licensed, trace = C.audit_inference(graph, "I3")
    assert licensed
    assert [step[2] for step in trace] == [True, True, True]
    assert "closedness is not required" in trace[2][3]

    graph.edges["EQ1"]["ring_iso_verdict"] = "UNVERIFIED"
    refused, refused_trace = C.audit_inference(graph, "I3")
    assert not refused
    assert "lacks current VERIFIED" in refused_trace[1][3]
    assert "no structured target-expressibility proof" in refused_trace[2][3]

    graph.edges["EQ1"]["ring_iso_verdict"] = V.ISO_VERIFIED
    graph.edges["EQ1"]["ring_iso"] = False
    refused, refused_trace = C.audit_inference(graph, "I3")
    assert not refused
    assert "lacks current VERIFIED" in refused_trace[1][3]


def test_predicate_pullback_preserves_identity_and_checked_projection_syntax():
    graph = _condition_graph("x", relation="NONZERO")
    graph.apply({
        "ev": "model", "id": "LOOSE", "what": "same-coordinate ambient",
        "characteristic": 0, "ring_vars": ["y", "x"],
        "generators": ["y*x-1", "y^2-x"],
    }, source="test", lineno=5)
    graph.apply({
        "ev": "edge", "id": "R", "src": "SOURCE", "dst": "LOOSE",
        "type": K.RESTRICTION, "map_kind": K.IDENTITY_MAP,
        "why": "forget an open side condition",
    }, source="test", lineno=6)

    graph.apply({
        "ev": "edge", "id": "N", "src": "SOURCE", "dst": "LOOSE",
        "type": K.NECESSARY_CONDITION, "map_kind": K.POLYNOMIAL,
        "why": "a polynomial point map whose expressions are not recorded",
    }, source="test", lineno=7)
    graph.apply({
        "ev": "claim", "id": "P-LOOSE", "model": "LOOSE",
        "kind": K.PREDICATE, "statement": "x is nonzero",
        "condition": {"all": [
            {"relation": "NONZERO", "expression": "x"},
        ]},
    }, source="test", lineno=8)
    graph.apply({
        "ev": "claim", "id": "P-TARGET", "model": "TARGET",
        "kind": K.PREDICATE, "statement": "x is nonzero",
        "condition": {"all": [
            {"relation": "NONZERO", "expression": "x"},
        ]},
    }, source="test", lineno=9)
    graph.apply({
        "ev": "inference", "id": "I-RESTRICT", "claim": "P-LOOSE",
        "path": [["R", K.AGAINST], ["E", K.ALONG]],
        "concludes_kind": K.PREDICATE,
        "asserted": "the ambient condition reaches the elimination target",
    }, source="test", lineno=10)
    graph.apply({
        "ev": "inference", "id": "I-PROJECT", "claim": "P-TARGET",
        "path": [["E", K.AGAINST], ["E", K.ALONG]],
        "concludes_kind": K.PREDICATE,
        "asserted": "projection pullback and section pushforward compose",
    }, source="test", lineno=11)
    graph.apply({
        "ev": "inference", "id": "I-NO-MAP", "claim": "P-LOOSE",
        "path": [["N", K.AGAINST], ["E", K.ALONG]],
        "concludes_kind": K.PREDICATE,
        "asserted": "an unspecified polynomial map rewrites the condition",
    }, source="test", lineno=12)
    graph.validate()


    restricted, restriction_trace = C.audit_inference(graph, "I-RESTRICT")
    assert restricted
    assert "literal identity point map" in restriction_trace[0][3]
    assert "closedness is not required" in restriction_trace[1][3]

    projected, projection_trace = C.audit_inference(graph, "I-PROJECT")
    assert projected
    assert "checked retained-coordinate projection" in projection_trace[0][3]
    assert "closedness is not required" in projection_trace[1][3]

    no_map, no_map_trace = C.audit_inference(graph, "I-NO-MAP")
    assert not no_map
    assert "no concrete identity or checked projection map" in no_map_trace[0][3]
    assert "no structured target-expressibility proof" in no_map_trace[1][3]

    graph.edges["E"]["output_verdict"] = "UNVERIFIED"
    unchecked, unchecked_trace = C.audit_inference(graph, "I-PROJECT")
    assert not unchecked
    assert "no concrete identity or checked projection map" in unchecked_trace[0][3]


def test_section_refuses_condition_naming_an_eliminated_coordinate():
    for relation in ("NONZERO", "ZERO"):
        graph = _condition_graph("y", relation=relation)

        assert not C.condition_expressible_at(
            graph, graph.claims["P"], "TARGET")
        licensed, trace = C.audit_inference(graph, "I")
        assert not licensed
        assert "no structured target-expressibility proof" in trace[0][3]


def test_section_refuses_unstructured_nonclosed_predicate():
    graph = _condition_graph()

    licensed, trace = C.audit_inference(graph, "I")
    assert not licensed
    assert "no structured target-expressibility proof" in trace[0][3]


def test_groebner_exactness_does_not_mint_point_surjectivity():
    graph = _condition_graph("x", relation="NONZERO")
    graph.edges["E"]["contraction_verdict"] = V.GROEBNER_VERIFIED

    assert C.effective_exact_contraction(graph.edges["E"])
    assert not C.effective_point_surjective(graph.edges["E"])
    licensed, trace = C.audit_inference(graph, "I")
    assert not licensed
    assert "only Zariski-closed conditions" in trace[0][3]


def test_structured_zero_condition_derives_closedness():
    graph = _condition_graph("x^2-1", relation="ZERO")

    assert C.structured_condition_closed(graph.claims["P"])
    licensed, _trace = C.audit_inference(graph, "I")
    assert licensed

    # Matching variable names on a manually asserted image map are not a
    # factorization proof. Only the constructor-built retained inclusion earns
    # automatic condition typing; legacy manual edges need their authored route.
    graph.edges["E"].pop("built_by_operation")
    manually_licensed, _manual_trace = C.audit_inference(graph, "I")
    assert not manually_licensed


def test_structured_condition_is_typed_in_its_source_ring():
    graph = _section_graph()
    graph.apply({"ev": "claim", "id": "P", "model": "SOURCE",
                 "kind": K.PREDICATE, "statement": "bad condition",
                 "condition": {"all": [
                     {"relation": "NONZERO", "expression": "z"},
                 ]}}, source="test", lineno=3)
    with pytest.raises(S.GraphError, match="not a polynomial"):
        graph.validate()


def test_structured_condition_rejects_an_open_ended_atom_schema():
    graph = _section_graph()
    with pytest.raises(S.GraphError, match="exactly `relation` and `expression`"):
        graph.apply({"ev": "claim", "id": "P", "model": "SOURCE",
                     "kind": K.PREDICATE, "statement": "bad condition",
                     "condition": {"all": [
                         {"relation": "NONZERO", "expression": "x",
                          "trusted": True},
                     ]}}, source="test", lineno=3)

def test_false_section_is_rejected_without_refuting_exactness():
    graph = S.Graph().apply_all([
        ({"ev": "model", "id": "SOURCE", "what": "source",
          "characteristic": 0, "ring_vars": ["y", "x"],
          "generators": ["x"]}, "test", 0),
        ({"ev": "model", "id": "TARGET", "what": "incomplete target",
          "characteristic": 0, "ring_vars": ["x"],
          "generators": [], "eliminated": ["y"]}, "test", 1),
        ({"ev": "edge", "id": "E", "src": "SOURCE", "dst": "TARGET",
          "type": K.IMAGE_CLOSURE, "map_kind": K.POLYNOMIAL,
          "why": "false elimination", "built_by_operation": "Eliminate"},
         "test", 2),
    ]).validate()

    class ZeroTargetBackend:
        def pullback_reduce(self, *_args, **_kwargs):
            return "x", False

    verdict, why, certificate = V.elimination_section(
        graph, "E", {"y": "0"}, _backend=ZeroTargetBackend())
    assert verdict == V.SECTION_REJECTED
    assert "not to zero" in why
    assert certificate is None
    assert not C.effective_exact_contraction(graph.edges["E"])


def test_section_must_live_in_retained_ring_before_backend_runs():
    graph = _section_graph()
    verdict, why, certificate = V.elimination_section(
        graph, "E", {"y": "y+x"}, _backend=object())
    assert verdict == V.SECTION_REJECTED
    assert "outside the retained ring" in why
    assert certificate is None
def test_verify_elimination_cli_passes_explicit_section(
        tmp_path, monkeypatch, capsys):
    seen = {}

    def fake(root, edge, section, timeout, record):
        seen.update(root=root, edge=edge, section=section,
                    timeout=timeout, record=record)
        return V.SECTION_VERIFIED, "checked", {"rows": []}

    monkeypatch.setattr(V, "verify_elimination_section", fake)
    status = cli.main([
        "--root", str(tmp_path), "verify-elimination", "E",
        "--section", '{"y":"x^2"}', "--timeout", "19", "--dry-run",
    ])

    assert status == 0
    assert "VERIFIED_SECTION" in capsys.readouterr().out
    assert seen == {
        "root": str(tmp_path), "edge": "E", "section": {"y": "x^2"},
        "timeout": 19, "record": False,
    }
def test_verify_elimination_groebner_cli_runs_the_producer(monkeypatch, capsys):
    called = {}

    def fake(root, edge, timeout=300, record=True):
        called.update(root=root, edge=edge, timeout=timeout, record=record)
        return V.GROEBNER_VERIFIED, "checked pure-lex proof", {"checked": {}}

    monkeypatch.setattr(V, "verify_elimination_groebner", fake)
    assert cli.main([
        "--root", "campaign", "verify-elimination-groebner", "E",
        "--timeout", "17", "--dry-run",
    ]) == 0
    assert called == {
        "root": "campaign", "edge": "E", "timeout": 17, "record": False,
    }
    assert "VERIFIED_GROEBNER" in capsys.readouterr().out