/-
# Operation contracts: semantics are stronger than local validation

An operation contract must keep three things separate:

  * the mathematical relation the operation intends to construct;
  * the weaker guarantee established by the available local checkers;
  * the transport consequences licensed by that checked guarantee.

If those collapse into one predicate, a successful translation-validation
check can silently become a theorem that the backend computed the complete
mathematical object.  Saturation is the first executable instance because the
current runtime makes the distinction concrete:

    source containment       I ⊆ J
    generator certificates  recorded generators of J lie in I : f^∞
    exact saturation         J = I : f^∞

The first two are checked independently.  They do not imply the third.
-/

import GrandPortage.Localization

namespace GrandPortage

universe u v w

/-- A backend-neutral semantic contract for one model-changing operation.

    `semanticRelation` says what a mathematically exact implementation means.
    `checkedGuarantee` says only what the current translation validators earn.
    The required theorem points from exact semantics to the checked guarantee,
    deliberately not in the tempting and generally false reverse direction.

    Preconditions may mention both endpoints. A computed target has
    well-formedness obligations of its own; forcing those into source data would
    hide exactly the output boundary this record is meant to expose. -/
structure OperationContract (Params : Type u) (Source : Type v)
    (Target : Type w) where
  precondition : Params → Source → Target → Prop
  semanticRelation : Params → Source → Target → Prop
  checkedGuarantee : Params → Source → Target → Prop
  semantics_entails_checked :
    ∀ p source target,
      precondition p source target →
      semanticRelation p source target →
      checkedGuarantee p source target

/-- The ideal generated by `generators`, characterized by its universal
    property inside a chosen family of admissible ideal predicates.

    `Ideal` is intentionally only a predicate in this Mathlib-free model.  The
    `isIdeal` parameter restores exactly the missing algebraic distinction:
    generated membership means membership in every admissible ideal containing
    the generators. -/
def GeneratedIdeal {R : Type u} (isIdeal : Ideal R → Prop)
    (generators : R → Prop) : Ideal R :=
  fun g => ∀ J, isIdeal J → (∀ x, generators x → J x) → J g

/-- Every named generator belongs to the ideal it generates. -/
theorem generator_mem_generated {R : Type u} {isIdeal : Ideal R → Prop}
    {generators : R → Prop} {g : R} (hg : generators g) :
    GeneratedIdeal isIdeal generators g := by
  intro J _ contains
  exact contains g hg

/-- The generated ideal is contained in every admissible ideal containing its
    generators.  This is the bridge the predicate-only model previously lacked. -/
theorem generatedIdeal_least {R : Type u} {isIdeal : Ideal R → Prop}
    {generators : R → Prop} {J : Ideal R}
    (hJ : isIdeal J) (contains : ∀ g, generators g → J g) :
    IdealGrows (GeneratedIdeal isIdeal generators) J := by
  intro g generated
  exact generated J hJ contains

/-- The semantic parameters of a saturation run embedding the polynomial
    inverted, the generators recorded at the runtime boundary, and the family
    of predicates that count as ideals in the source ring. -/
structure SaturationParams (R : Type u) where
  f : R
  recordedGenerator : R → Prop
  isIdeal : Ideal R → Prop

/-- The exact meaning of a saturation result `J`: membership in `J` is
    precisely membership in `I : f^∞`. -/
def SaturationSemantics {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R) : Prop :=
  ∀ g, J g ↔ SatMem I p.f g

/-- Endpoint facts needed to interpret the local checks.  Both endpoints and
    the semantic saturation are admissible ideals, and the output predicate is
    exactly the ideal generated by the list recorded at the runtime boundary. -/
structure SaturationPrecondition {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R) : Prop where
  one_mul : ∀ g : R, 1 * g = g
  source_is_ideal : p.isIdeal I
  output_is_ideal : p.isIdeal J
  saturation_is_ideal : p.isIdeal (fun g => SatMem I p.f g)
  output_generated :
    ∀ g, J g ↔ GeneratedIdeal p.isIdeal p.recordedGenerator g

/-- Exactly what Grand Portage's two independent runtime checks establish.

    `containsSource` is the edge-containment check. `noInventedGenerator` is
    the operation-output certificate for each recorded generator.  The theorem
    `saturation_checked_no_invented_elements` combines these local facts with
    `output_generated` to derive the stronger ideal-level sound envelope. -/
structure SaturationChecked {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R) : Prop where
  containsSource : IdealGrows I J
  noInventedGenerator : ∀ g, p.recordedGenerator g → SatMem I p.f g

/-- Ordinary ideal membership gives saturation membership whenever `1` acts
    as a left identity.  This generalizes `mem_satMem` beyond `Int` without
    importing Mathlib's algebraic hierarchy. -/
theorem mem_satMem_of_one_mul {R : Type u} [Mul R] [OfNat R 1]
    (one_mul : ∀ g : R, 1 * g = g) {I : Ideal R} {f g : R}
    (h : I g) : SatMem I f g :=
  ⟨1, PowerOf.one, by rw [one_mul]; exact h⟩

/-- Exact saturation entails both checks for every well-formed recorded
    generator list. -/
theorem saturation_semantics_entails_checked
    {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R)
    (pre : SaturationPrecondition p I J)
    (h : SaturationSemantics p I J) :
    SaturationChecked p I J := by
  constructor
  · intro g hg
    exact (h g).2 (mem_satMem_of_one_mul pre.one_mul hg)
  · intro g recorded
    apply (h g).1
    apply (pre.output_generated g).2
    exact generator_mem_generated recorded

/-- Generator certificates lift to every element of the recorded output ideal
    once the endpoint is known to be generated by exactly those generators.

    This proves the sound envelope `J ⊆ I : f^∞`.  It does not prove the open
    completeness direction `I : f^∞ ⊆ J`. -/
theorem saturation_checked_no_invented_elements
    {R : Type u} [Mul R] [OfNat R 1]
    {p : SaturationParams R} {I J : Ideal R}
    (pre : SaturationPrecondition p I J)
    (checked : SaturationChecked p I J) :
    IdealGrows J (fun g => SatMem I p.f g) := by
  intro g hg
  have generated := (pre.output_generated g).1 hg
  exact generated
    (fun x => SatMem I p.f x)
    pre.saturation_is_ideal
    checked.noInventedGenerator

/-- Saturation as an operation-contract instance. -/
def saturationContract {R : Type u} [Mul R] [OfNat R 1] :
    OperationContract (SaturationParams R) (Ideal R) (Ideal R) where
  precondition := SaturationPrecondition
  semanticRelation := SaturationSemantics
  checkedGuarantee := SaturationChecked
  semantics_entails_checked := saturation_semantics_entails_checked

/-! ## Elimination: the first genuinely multi-sorted contract

The source ideal lives in `R`; the recorded elimination ideal lives in the
retained-coordinate ring `S`. `embedding : S → R` is the coordinate inclusion.
Typing a generator as an element of `S` makes runtime expressibility a type
boundary rather than another Boolean hypothesis. -/

/-- Contraction of a source ideal along the retained-coordinate inclusion. -/
def ContractIdeal {R : Type u} {S : Type v}
    (embedding : S → R) (I : Ideal R) : Ideal S :=
  fun g => I (embedding g)

/-- Parameters retained at the elimination boundary. -/
structure EliminationParams (R : Type u) (S : Type v) where
  embedding : S → R
  recordedGenerator : S → Prop
  sourceIdeal : Ideal R → Prop
  targetIdeal : Ideal S → Prop

/-- Exact elimination means equality with the contraction `ι⁻¹(I)`. -/
def EliminationSemantics {R : Type u} {S : Type v}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S) : Prop :=
  ∀ g, J g ↔ I (p.embedding g)

/-- Endpoint facts needed to lift generator certificates to an ideal theorem. -/
structure EliminationPrecondition {R : Type u} {S : Type v}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S) : Prop where
  source_is_ideal : p.sourceIdeal I
  output_is_ideal : p.targetIdeal J
  contraction_is_ideal : p.targetIdeal (ContractIdeal p.embedding I)
  output_generated :
    ∀ g, J g ↔ GeneratedIdeal p.targetIdeal p.recordedGenerator g

/-- What the cheap translation validator establishes: no recorded equation was
    invented. Runtime expressibility is represented here by the generator
    already having type `S`. -/
structure EliminationChecked {R : Type u} {S : Type v}
    (p : EliminationParams R S) (I : Ideal R) (_J : Ideal S) : Prop where
  noInventedGenerator :
    ∀ g, p.recordedGenerator g → I (p.embedding g)

/-- Exact contraction entails the local generator certificates. -/
theorem elimination_semantics_entails_checked
    {R : Type u} {S : Type v}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S)
    (pre : EliminationPrecondition p I J)
    (exact : EliminationSemantics p I J) :
    EliminationChecked p I J := by
  constructor
  intro g recorded
  apply (exact g).1
  apply (pre.output_generated g).2
  exact generator_mem_generated recorded

/-- Generator certificates lift to the sound envelope
    `J ⊆ embedding⁻¹(I)`. The reverse inclusion is still open. -/
theorem elimination_checked_no_invented_elements
    {R : Type u} {S : Type v}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (pre : EliminationPrecondition p I J)
    (checked : EliminationChecked p I J) :
    IdealGrows J (ContractIdeal p.embedding I) := by
  intro g hg
  have generated := (pre.output_generated g).1 hg
  exact generated
    (ContractIdeal p.embedding I)
    pre.contraction_is_ideal
    checked.noInventedGenerator

/-- Elimination as a multi-sorted operation-contract instance. -/
def eliminationContract {R : Type u} {S : Type v} :
    OperationContract (EliminationParams R S) (Ideal R) (Ideal S) where
  precondition := EliminationPrecondition
  semanticRelation := EliminationSemantics
  checkedGuarantee := EliminationChecked
  semantics_entails_checked := elimination_semantics_entails_checked

/-- The checked one-sided envelope licenses pulling a target identity back to
    the source coordinate ring. -/
theorem elimination_checked_transports_identity_against
    {R : Type u} {S : Type v} [Sub R] [Sub S]
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (include_sub : ∀ a b : S,
      p.embedding (a - b) = p.embedding a - p.embedding b)
    (pre : EliminationPrecondition p I J)
    (checked : EliminationChecked p I J)
    {lhs rhs : S} :
    EqMod J lhs rhs → EqMod I (p.embedding lhs) (p.embedding rhs) := by
  have carries : Carries p.embedding J I := by
    intro g hg
    exact elimination_checked_no_invented_elements pre checked g hg
  exact eqMod_transports p.embedding include_sub carries

/-- The opposite identity direction uses the missing completeness half of exact
    semantics; it is intentionally not derivable from `EliminationChecked`. -/
theorem elimination_semantics_transports_identity_along
    {R : Type u} {S : Type v} [Sub R] [Sub S]
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (include_sub : ∀ a b : S,
      p.embedding (a - b) = p.embedding a - p.embedding b)
    (exact : EliminationSemantics p I J)
    {lhs rhs : S} :
    EqMod I (p.embedding lhs) (p.embedding rhs) → EqMod J lhs rhs := by
  intro h
  apply (exact (lhs - rhs)).2
  rwa [include_sub]
/-- The missing half of elimination exactness: every source relation that is
    expressible in the retained ring was recorded in the target ideal. -/
def EliminationCompleteness {R : Type u} {S : Type v}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S) : Prop :=
  IdealGrows (ContractIdeal p.embedding I) J

/-- The cheap no-invention check and an independently earned completeness
    certificate combine to recover exact contraction semantics. -/
theorem elimination_checked_and_complete_semantics
    {R : Type u} {S : Type v}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (pre : EliminationPrecondition p I J)
    (checked : EliminationChecked p I J)
    (complete : EliminationCompleteness p I J) :
    EliminationSemantics p I J := by
  intro g
  constructor
  · exact elimination_checked_no_invented_elements pre checked g
  · exact complete g

/-- A polynomial section is stronger than bare completeness. Runtime checks
    instantiate `retract` by simultaneous polynomial substitution, fix every
    retained coordinate literally, and certify that every recorded source
    generator maps into the target ideal. `source_generated` and
    `preimage_is_ideal` are the abstract bridge showing those finite checks
    carry the entire source ideal; polynomial substitution supplies the latter
    because inverse images of ideals under ring homomorphisms are ideals. -/
structure EliminationSectionCertificate {R : Type u} {S : Type v}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S) where
  retract : R → S
  retract_embedding : ∀ g, retract (p.embedding g) = g
  sourceGenerator : R → Prop
  source_generated :
    ∀ f, I f ↔ GeneratedIdeal p.sourceIdeal sourceGenerator f
  preimage_is_ideal : p.sourceIdeal (fun f => J (retract f))
  carries_source_generator :
    ∀ f, sourceGenerator f → J (retract f)

/-- The finite generator certificates lift through ideal generation, and the
    checked polynomial section therefore proves contraction completeness. -/
theorem elimination_section_entails_completeness
    {R : Type u} {S : Type v}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (certificate : EliminationSectionCertificate p I J) :
    EliminationCompleteness p I J := by
  intro g hg
  rw [← certificate.retract_embedding g]
  have generated := (certificate.source_generated (p.embedding g)).1 hg
  exact generated
    (fun f => J (certificate.retract f))
    certificate.preimage_is_ideal
    certificate.carries_source_generator

/-- A valued affine point is a valid evaluation that kills every element of the
    model ideal. `validEvaluation` is the abstract stand-in for a ring/algebra
    homomorphism in this Mathlib-free development; the value type `A` keeps the
    coefficient algebra explicit. -/
structure AffinePoint {R : Type u} {A : Type w}
    (validEvaluation : (R -> A) -> Prop) (zero : A) (I : Ideal R) where
  eval : R -> A
  valid : validEvaluation eval
  vanishes : forall f, I f -> eval f = zero

/-- Point-surjectivity of the elimination projection over one coefficient
    algebra: every target-valued point has a source-valued lift whose retained
    coordinates are unchanged. -/
def EliminationPointSurjective {R : Type u} {S : Type v} {A : Type w}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S)
    (sourceEvaluation : (R -> A) -> Prop)
    (targetEvaluation : (S -> A) -> Prop) (zero : A) : Prop :=
  forall q : AffinePoint targetEvaluation zero J,
    Exists fun sourcePoint : AffinePoint sourceEvaluation zero I =>
      forall g : S, sourcePoint.eval (p.embedding g) = q.eval g

/-- A polynomial section is point-level evidence, not merely ideal evidence.

    Runtime polynomial substitution supplies `precompose_valid`: composing a
    target algebra evaluation with the checked polynomial retraction is again a
    valid source evaluation. Generator membership then makes that lift satisfy
    the entire source ideal, and `retract_embedding` proves that projecting it
    recovers the original target point. -/
theorem elimination_section_entails_point_surjectivity
    {R : Type u} {S : Type v} {A : Type w}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (certificate : EliminationSectionCertificate p I J)
    (sourceEvaluation : (R -> A) -> Prop)
    (targetEvaluation : (S -> A) -> Prop) (zero : A)
    (precompose_valid :
      forall (q : S -> A), targetEvaluation q ->
        sourceEvaluation (fun f => q (certificate.retract f))) :
    EliminationPointSurjective p I J
      sourceEvaluation targetEvaluation zero := by
  intro q
  let liftEval : R -> A := fun f => q.eval (certificate.retract f)
  have liftValid : sourceEvaluation liftEval :=
    precompose_valid q.eval q.valid
  have liftVanishes : forall f, I f -> liftEval f = zero := by
    intro f hf
    have generated := (certificate.source_generated f).1 hf
    have mapped : J (certificate.retract f) := generated
      (fun x => J (certificate.retract x))
      certificate.preimage_is_ideal
      certificate.carries_source_generator
    exact q.vanishes (certificate.retract f) mapped
  let lifted : AffinePoint sourceEvaluation zero I := {
    eval := liftEval
    valid := liftValid
    vanishes := liftVanishes
  }
  refine Exists.intro lifted ?_
  intro g
  change q.eval (certificate.retract (p.embedding g)) = q.eval g
  rw [certificate.retract_embedding]

/-- One partial point lift, defined on a predicate over target points.

    Runtime chart certificates instantiate `domain` by a principal-open
    condition (a guard is nonzero) or by the final closed fallback (all guards
    vanish). Rational formulas and ideal-membership certificates establish
    `lift` and `projects`; the semantic kernel only needs this contract. -/
structure PartialEliminationPointLift
    {R : Type u} {S : Type v} {A : Type w}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S)
    (sourceEvaluation : (R -> A) -> Prop)
    (targetEvaluation : (S -> A) -> Prop) (zero : A) where
  domain : AffinePoint targetEvaluation zero J -> Prop
  lift :
    forall q : AffinePoint targetEvaluation zero J, domain q ->
      AffinePoint sourceEvaluation zero I
  projects :
    forall (q : AffinePoint targetEvaluation zero J) (hq : domain q)
      (g : S), (lift q hq).eval (p.embedding g) = q.eval g

/-- A finite family of partial lifts covers the target point set. Keeping
    coverage separate from each chart is the n-ary inference boundary: no
    individual chart claims global authority. -/
structure FiniteEliminationPointLiftCover
    {R : Type u} {S : Type v} {A : Type w}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S)
    (sourceEvaluation : (R -> A) -> Prop)
    (targetEvaluation : (S -> A) -> Prop) (zero : A) where
  charts : List (PartialEliminationPointLift p I J
    sourceEvaluation targetEvaluation zero)
  covers :
    forall q : AffinePoint targetEvaluation zero J,
      Exists fun chart => chart ∈ charts ∧ chart.domain q

/-- Finite checked partial lifts plus their joint coverage entail the same
    point-surjectivity proposition as a global polynomial section. -/
theorem finite_lift_cover_entails_point_surjectivity
    {R : Type u} {S : Type v} {A : Type w}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    {sourceEvaluation : (R -> A) -> Prop}
    {targetEvaluation : (S -> A) -> Prop} {zero : A}
    (certificate : FiniteEliminationPointLiftCover p I J
      sourceEvaluation targetEvaluation zero) :
    EliminationPointSurjective p I J
      sourceEvaluation targetEvaluation zero := by
  intro q
  obtain ⟨chart, _inCover, hq⟩ := certificate.covers q
  exact ⟨chart.lift q hq, chart.projects q hq⟩
/-- A source predicate is expressible in the retained coordinates when it is
    the pullback of a target predicate: evaluations agreeing on every embedded
    retained coordinate give the same proposition. This is the semantic object
    that the runtime's structured exact-affine condition syntax approximates. -/
def RetainedCoordinateExpressible {R : Type u} {S : Type v} {A : Type w}
    (p : EliminationParams R S)
    (sourcePredicate : (R -> A) -> Prop)
    (targetPredicate : (S -> A) -> Prop) : Prop :=
  forall (sourceEval : R -> A) (targetEval : S -> A),
    (forall g : S, sourceEval (p.embedding g) = targetEval g) ->
      (sourcePredicate sourceEval ↔ targetPredicate targetEval)

/-- Point-surjectivity transports every predicate that factors through the
    retained coordinates. Closedness is irrelevant here: equations and
    nonvanishing conditions use the same point-lifting argument. -/
theorem point_surjectivity_transports_retained_predicate
    {R : Type u} {S : Type v} {A : Type w}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    {sourceEvaluation : (R -> A) -> Prop}
    {targetEvaluation : (S -> A) -> Prop} {zero : A}
    {sourcePredicate : (R -> A) -> Prop}
    {targetPredicate : (S -> A) -> Prop}
    (surjective : EliminationPointSurjective p I J
      sourceEvaluation targetEvaluation zero)
    (expressible : RetainedCoordinateExpressible
      p sourcePredicate targetPredicate)
    (holdsOnSource :
      forall sourcePoint : AffinePoint sourceEvaluation zero I,
        sourcePredicate sourcePoint.eval) :
    forall targetPoint : AffinePoint targetEvaluation zero J,
      targetPredicate targetPoint.eval := by
  intro targetPoint
  obtain ⟨sourcePoint, projectsTo⟩ := surjective targetPoint
  exact (expressible sourcePoint.eval targetPoint.eval projectsTo).mp
    (holdsOnSource sourcePoint)
/-! ## General Gröbner completeness boundary

The polynomial-section certificate above is powerful but special: many exact
eliminations have no polynomial section. The general runtime route proposes a
basis in an elimination order and checks finite ideal-membership identities
plus a standard representation for every S-pair.

This file deliberately does not pretend to formalize Buchberger's criterion.
`EliminationBasisProperty` below names exactly the algebraic theorem that a
sound polynomial checker earns from those finite traces. The subsequent bridge
from that property to contraction completeness is proved here and is
independent of Singular, polynomial syntax, and monomial implementation.
-/

/-- Predicate presented by a finite runtime list. -/
def Listed {R : Type u} (xs : List R) : R → Prop :=
  fun x => x ∈ xs

/-- Endpoint interpretation facts together with the finite facts checked at the
source/basis/target boundary.

`source_generated` interprets the recorded source list as `I`, while
`basis_span_is_ideal` supplies algebraic infrastructure for `GeneratedIdeal`;
the runtime checker directly replays the generator memberships. Only the
direction needed for completeness is retained. The independent no-invention
operation verdict proves the reverse contraction inclusion. -/
structure EliminationBasisBoundary {R : Type u} {S : Type v}
    (p : EliminationParams R S) (I : Ideal R) (J : Ideal S) where
  sourceGenerators : List R
  basis : List R
  retainedBasis : List S
  source_generated :
    ∀ f, I f ↔
      GeneratedIdeal p.sourceIdeal (Listed sourceGenerators) f
  basis_span_is_ideal :
    p.sourceIdeal (GeneratedIdeal p.sourceIdeal (Listed basis))
  source_generator_in_basis_span :
    ∀ f, Listed sourceGenerators f →
      GeneratedIdeal p.sourceIdeal (Listed basis) f
  retained_generator_in_output :
    ∀ h, Listed retainedBasis h → J h

/-- The conclusion supplied by Buchberger's criterion plus the elimination
theorem: a retained element of the basis span is generated by the retained
subbasis.

This is not a field a runtime certificate may assert. A checker-soundness
theorem must derive it from the exact coefficient field, elimination order,
complete S-pair traces, and checker-derived retained subbasis. -/
def EliminationBasisProperty {R : Type u} {S : Type v}
    (p : EliminationParams R S)
    (basis : List R) (retainedBasis : List S) : Prop :=
  ∀ g,
    GeneratedIdeal p.sourceIdeal (Listed basis) (p.embedding g) →
    GeneratedIdeal p.targetIdeal (Listed retainedBasis) g

/-- The checked source generators place every source-ideal element in the
candidate basis span. -/
theorem elimination_basis_spans_source
    {R : Type u} {S : Type v}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (facts : EliminationBasisBoundary p I J) :
    ∀ f, I f →
      GeneratedIdeal p.sourceIdeal (Listed facts.basis) f := by
  intro f hf
  have generated := (facts.source_generated f).1 hf
  exact generated
    (GeneratedIdeal p.sourceIdeal (Listed facts.basis))
    facts.basis_span_is_ideal
    facts.source_generator_in_basis_span

/-- Finite boundary checks plus the algebraic elimination property prove the
missing contraction inclusion. Combined with
`elimination_checked_no_invented_elements`, this feeds
`elimination_checked_and_complete_semantics`. -/
theorem elimination_basis_entails_completeness
    {R : Type u} {S : Type v}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (pre : EliminationPrecondition p I J)
    (facts : EliminationBasisBoundary p I J)
    (elimination :
      EliminationBasisProperty p facts.basis facts.retainedBasis) :
    EliminationCompleteness p I J := by
  intro g hg
  have inBasis :
      GeneratedIdeal p.sourceIdeal
        (Listed facts.basis) (p.embedding g) :=
    elimination_basis_spans_source facts (p.embedding g) hg
  have inRetained := elimination g inBasis
  exact inRetained J pre.output_is_ideal facts.retained_generator_in_output

/-- The runtime's polynomial-section route: local no-invention plus the checked
    section recovers exact contraction semantics. -/
theorem elimination_checked_and_section_semantics
    {R : Type u} {S : Type v}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (pre : EliminationPrecondition p I J)
    (checked : EliminationChecked p I J)
    (certificate : EliminationSectionCertificate p I J) :
    EliminationSemantics p I J :=
  elimination_checked_and_complete_semantics
    pre checked (elimination_section_entails_completeness certificate)

/-- The runtime's pure-lex certificate route: the same local no-invention
    guarantee composes with independently checked basis completeness. The
    algorithm producing the basis is irrelevant once these premises hold. -/
theorem elimination_checked_and_basis_semantics
    {R : Type u} {S : Type v}
    {p : EliminationParams R S} {I : Ideal R} {J : Ideal S}
    (pre : EliminationPrecondition p I J)
    (checked : EliminationChecked p I J)
    (facts : EliminationBasisBoundary p I J)
    (elimination :
      EliminationBasisProperty p facts.basis facts.retainedBasis) :
    EliminationSemantics p I J :=
  elimination_checked_and_complete_semantics pre checked
    (elimination_basis_entails_completeness pre facts elimination)
/-! ## What the checked guarantee licenses -/

/-- Source identities remain valid on the checked saturation result.  This is
    the `NECESSARY_CONDITION / AGAINST / IDENTITY` theorem for saturation,
    derived from the independently checked `containsSource` field. -/
theorem saturation_checked_transports_identity_against
    {R : Type u} [Mul R] [OfNat R 1] [Sub R]
    {p : SaturationParams R} {I J : Ideal R}
    (checked : SaturationChecked p I J) {lhs rhs : R} :
    EqMod I lhs rhs → EqMod J lhs rhs :=
  eqMod_against checked.containsSource

/-! ## And what it does not license -/

/-- A single recorded generator for the ideal `(6)`. -/
def sixGenerator : Int → Prop := fun n => n = 6

/-- Saturation at `2`, with `(6)` recorded by its generator `6`. -/
def sixesSaturationIdeal : Ideal Int := fun g => SatMem sixes 2 g

/-- A tiny admissible-ideal family sufficient to exercise the universal
    generated-ideal bridge on the concrete `(6)` counterexample. -/
def sixesIdealTheory : Ideal Int → Prop :=
  fun J => J = sixes ∨ J = sixesSaturationIdeal

/-- In that family, the ideal generated by `6` is exactly `(6)`. -/
theorem sixes_is_generated :
    ∀ g, sixes g ↔ GeneratedIdeal sixesIdealTheory sixGenerator g := by
  intro g
  constructor
  · intro hg J hJ contains
    rcases hJ with hJ | hJ
    · rw [hJ]
      exact hg
    · rw [hJ]
      exact mem_satMem hg
  · intro generated
    apply generated sixes (Or.inl rfl)
    intro x recorded
    simp only [sixGenerator] at recorded
    subst x
    exact ⟨1, by omega⟩

/-- Saturation at `2`, with `(6)` recorded by its generator `6`. -/
def sixesSaturationParams : SaturationParams Int where
  f := 2
  recordedGenerator := sixGenerator
  isIdeal := sixesIdealTheory

/-- The recorded generator really belongs to the declared output ideal. -/
theorem sixes_saturation_precondition :
    SaturationPrecondition sixesSaturationParams sixes sixes := by
  refine {
    one_mul := Int.one_mul
    source_is_ideal := Or.inl rfl
    output_is_ideal := Or.inl rfl
    saturation_is_ideal := Or.inr rfl
    output_generated := sixes_is_generated
  }

/-- The unchanged ideal `(6)` passes both local checks: it contains the source
    and its recorded generator has a saturation witness. -/
theorem sixes_checked_as_output :
    SaturationChecked sixesSaturationParams sixes sixes := by
  constructor
  · intro g hg
    exact hg
  · intro g recorded
    simp only [sixesSaturationParams, sixGenerator] at recorded
    subst g
    exact mem_satMem ⟨1, by omega⟩

/-- The same local checks now earn an ideal-level soundness envelope: every
    element generated by the recorded output lies in the true saturation. -/
theorem sixes_checked_has_no_invented_elements :
    IdealGrows sixes sixesSaturationIdeal :=
  saturation_checked_no_invented_elements
    sixes_saturation_precondition sixes_checked_as_output

/-- But that checked output is not the exact saturation: `3` is in
    `(6) : 2^∞` and not in `(6)`. Thus local validation cannot be promoted to
    exact operation semantics. -/
theorem checked_does_not_imply_saturation_semantics :
    ¬ SaturationSemantics sixesSaturationParams sixes sixes := by
  intro h
  exact three_not_mem_sixes ((h 3).2 three_satMem_sixes)

/-- Even exact saturation does not let a derived identity travel back to the
    ambient ideal.  This pins the refused ALONG direction independently of the
    implementation or its local checker. -/
theorem exact_saturation_does_not_transport_identity_along :
    let saturated : Ideal Int := fun g => SatMem sixes 2 g
    SaturationSemantics sixesSaturationParams sixes saturated ∧
      EqMod saturated 3 0 ∧ ¬ EqMod sixes 3 0 := by
  dsimp [SaturationSemantics, sixesSaturationParams]
  constructor
  · intro g
    rfl
  constructor
  · simpa [EqMod] using three_satMem_sixes
  · simpa [EqMod] using three_not_mem_sixes
/-! ## Elimination completeness is genuinely additional authority -/

/-- An empty recorded generator set, representing the zero ideal output. -/
def noEliminationGenerators : Int → Prop := fun _ => False

/-- A tiny target-ideal theory containing the zero ideal and `(2)`. -/
def eliminationIdealTheory : Ideal Int → Prop :=
  fun J => J = zeroI ∨ J = evens

/-- In that theory, the empty set generates exactly the zero ideal. -/
theorem zeroI_is_generated_by_none :
    ∀ g, zeroI g ↔
      GeneratedIdeal eliminationIdealTheory noEliminationGenerators g := by
  intro g
  constructor
  · intro hg J hJ _
    rcases hJ with hJ | hJ
    · rw [hJ]
      exact hg
    · rw [hJ]
      simp only [zeroI] at hg
      subst g
      exact ⟨0, by omega⟩
  · intro generated
    apply generated zeroI (Or.inl rfl)
    intro x impossible
    exact False.elim impossible

/-- The deliberately incomplete output: source `(2)`, recorded target `(0)`. -/
def incompleteEliminationParams : EliminationParams Int Int where
  embedding := id
  recordedGenerator := noEliminationGenerators
  sourceIdeal := eliminationIdealTheory
  targetIdeal := eliminationIdealTheory

/-- The endpoint is well formed and generated by exactly the empty output. -/
theorem incomplete_elimination_precondition :
    EliminationPrecondition incompleteEliminationParams evens zeroI := by
  refine {
    source_is_ideal := Or.inr rfl
    output_is_ideal := Or.inl rfl
    contraction_is_ideal := Or.inr ?_
    output_generated := zeroI_is_generated_by_none
  }
  rfl

/-- The cheap generator check passes vacuously. -/
theorem incomplete_elimination_checked :
    EliminationChecked incompleteEliminationParams evens zeroI := by
  constructor
  intro g impossible
  exact False.elim impossible

/-- But the output is not the contraction: `2` was missed. -/
theorem checked_does_not_imply_elimination_semantics :
    ¬ EliminationSemantics incompleteEliminationParams evens zeroI := by
  intro exact
  have evenTwo : evens 2 := ⟨1, by omega⟩
  have zeroTwo : zeroI 2 := (exact 2).2 evenTwo
  simp only [zeroI] at zeroTwo
  omega

/-- The same witness shows that completeness itself is not hidden inside the
    cheap checked guarantee. -/
theorem incomplete_elimination_has_no_completeness :
    Not (EliminationCompleteness incompleteEliminationParams evens zeroI) := by
  intro complete
  have evenTwo : evens 2 := ⟨1, by omega⟩
  have zeroTwo : zeroI 2 := complete 2 evenTwo
  simp only [zeroI] at zeroTwo
  omega
/-- Consequently the locally checked output cannot carry the source identity
    `2 = 0` along to the incomplete target. -/
theorem checked_elimination_does_not_transport_identity_along :
    EliminationChecked incompleteEliminationParams evens zeroI ∧
      EqMod evens 2 0 ∧ ¬ EqMod zeroI 2 0 := by
  constructor
  · exact incomplete_elimination_checked
  constructor
  · simp only [EqMod, evens]
    exact ⟨1, by omega⟩
  · simp only [EqMod, zeroI]
    omega

/-- A point semantics with no admissible source evaluations. This tiny abstract
    countermodel isolates the logical gap that the hyperbola supplies
    geometrically at runtime: ideal equality alone contains no point-lifting
    theorem. -/
def noValidEvaluation : (Int -> Unit) -> Prop := fun _ => False

def anyValidEvaluation : (Int -> Unit) -> Prop := fun _ => True

/-- Exact contraction does not imply point-surjectivity. The additional
    polynomial-section structure is load-bearing, not a different spelling of
    ideal equality. -/
theorem exact_contraction_does_not_imply_point_surjectivity :
    EliminationSemantics incompleteEliminationParams zeroI zeroI ∧
      Not (EliminationPointSurjective
        incompleteEliminationParams zeroI zeroI
        noValidEvaluation anyValidEvaluation ()) := by
  constructor
  · intro g
    rfl
  · intro surjective
    let target : AffinePoint anyValidEvaluation () zeroI := {
      eval := fun _ => ()
      valid := True.intro
      vanishes := by
        intro _ _
        rfl
    }
    obtain ⟨sourcePoint, _⟩ := surjective target
    exact sourcePoint.valid

/-- Even a point-surjective map does not transport an unrelated target
    predicate. The factorization through retained coordinates is load-bearing. -/
theorem point_surjectivity_needs_retained_expressibility :
    EliminationPointSurjective
        incompleteEliminationParams zeroI zeroI
        anyValidEvaluation anyValidEvaluation () ∧
      (forall _sourcePoint : AffinePoint anyValidEvaluation () zeroI,
        True) ∧
      Not (RetainedCoordinateExpressible
        incompleteEliminationParams
        (fun _ : Int -> Unit => True) (fun _ : Int -> Unit => False)) ∧
      Not (forall _targetPoint : AffinePoint anyValidEvaluation () zeroI,
        False) := by
  constructor
  · intro targetPoint
    exact ⟨targetPoint, fun _ => rfl⟩
  constructor
  · intro _
    trivial
  constructor
  · intro expressible
    exact (expressible (fun _ => ()) (fun _ => ()) (fun _ => rfl)).mp
      True.intro
  · intro impossible
    let target : AffinePoint anyValidEvaluation () zeroI := {
      eval := fun _ => ()
      valid := True.intro
      vanishes := by
        intro _ _
        rfl
    }
    exact impossible target
end GrandPortage
